# Generated by Django 5.0.6 on 2026-08-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('first_registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Numéro enregistré',
                'verbose_name_plural': 'Registre des numéros',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
