# Generated by Django 5.0.6 on 2026-08-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneregistry',
            options={'ordering': ['-last_seen_at'], 'verbose_name': 'Compte', 'verbose_name_plural': 'Comptes'},
        ),
        migrations.AddField(
            model_name='phoneregistry',
            name='auth_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='phoneregistry',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
