# Generated by Django 5.0.6 on 2026-08-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_phoneregistry_options_phoneregistry_auth_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneregistry',
            old_name='password_hash',
            new_name='pin_hash',
        ),
    ]
