# Generated by Django 5.0.6 on 2026-08-12 00:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteQueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_number', models.CharField(db_index=True, max_length=32)),
                ('recipient_number', models.CharField(db_index=True, max_length=32)),
                ('group_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_message_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suppression en attente',
                'verbose_name_plural': 'Suppressions en attente',
                'ordering': ['created_at'],
            },
        ),
    ]
