# Generated by Django 5.0.6 on 2026-08-10 04:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextQueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_number', models.CharField(db_index=True, max_length=32)),
                ('recipient_number', models.CharField(db_index=True, max_length=32)),
                ('content', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('DELIVERED', 'Livré')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Message texte en attente',
                'verbose_name_plural': 'Messages texte en attente',
                'ordering': ['created_at'],
            },
        ),
    ]
