# Generated by Django 5.0.6 on 2026-08-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioqueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioqueueentry',
            name='group_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
