# Generated by Django 5.0.6 on 2026-08-10 17:08

import django.core.files.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaQueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_number', models.CharField(db_index=True, max_length=32)),
                ('recipient_number', models.CharField(db_index=True, max_length=32)),
                ('media_kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo')], max_length=8)),
                ('media_file', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(location='/home/claude/wakh-server/media/queued_media'), upload_to='')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('DELIVERED', 'Livré')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Média en attente',
                'verbose_name_plural': 'Médias en attente',
                'ordering': ['created_at'],
            },
        ),
    ]
