# Generated by Django 5.0.6 on 2026-08-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaqueue', '0002_mediaqueueentry_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaqueueentry',
            name='original_file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mediaqueueentry',
            name='media_kind',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document')], max_length=8),
        ),
    ]
